### ISSUE TITLE
Soporte para búsqueda dentro de los límites especificados por el usuario.

### ISSUE THREAD

**Issue by jon85p** [jon85p/pyENL#1]
La función solver() debe buscar solamente dentro del intervalo que es definido con las llaves {} en cada fichero de texto.

**Comment by xmagor** [comment]
Por ahora los límites están para asignar el guess inicial dentro de ese rango, pero scipy.opt.root pareciera que no permitiera limitar el rango de los guesses, solamente recive el guess inicial.
