### ISSUE TITLE
Soporte para bloques.

### ISSUE THREAD

**Issue by jon85p** [jon85p/pyENL#2]
La función solver() debe interpretar los distintos bloques que se encuentren en el sistema de ecuaciones donde cada bloque consiste en un set de ecuaciones que ya son solucionables, esto con el fin de acortar los tiempos de cálculo.
Por ejemplo:
- x^2 + y^2 = 1
- x + y = 1
- x*z = 2
- En este caso las dos primeras ecuaciones se consideran un solo bloque ya que de el sistema que conforma estas dos ecuciones se pueden tener los valores de dos variables ("x" y "y") para poder solucionar con facilidad la tercera ecuación.

**Comment by jon85p** [comment]
Muy probable uso de algoritmo de Tarjan (1952) 
[Implementación](http://ece.arizona.edu/~cellier/ece449_ppt5.pdf)
Desde la página 33 de este pdf se ve muy bien su uso: http://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=4573&context=etd

**Comment by darthcoder** [comment]
Hi, I'd like to offer help, but I am still learning python. Also I don't understand Spanish(I am just guessing the language, sorry if I'm wrong). I could help with the documentation etc.
