### ISSUE TITLE
Estructura de archivo de guardado.

### ISSUE THREAD

**Issue by jon85p** [jon85p/pyENL#22]
Un fichero comprimido con la siguiente estructura propuesta:
(cada título en negrita es un directorio, cada elemento listado un archivo)
(títulos en negrita más pequeños son subdirectorios)

# File.zip
- index.txt
 ## src
- eqn1.txt           -> Solo este archivo en betas, en otras versiones usar varios sistemas de ecuaciones
- eqn2.txt
- eqn3.txt

## vars
- vars1.dat
- vars2.dat
- vars3.dat

## imgs
- usr1.jpg -> Imágenes del usuario
- blabla.png

### -> tables
   - table1.dat -> Tablas calculadas del usuario
   - table2.dat
  ### -> graphs
  - graph1.dat -> Gráficas generadas y asociadas a las tablas
  - graph2.dat

**Comment by xmagor** [comment]
Implementado SRC y VARS , el resto se deja para futuras versiones
