### ISSUE TITLE
Guardar o abrir formato .enl con simbolo °

### ISSUE THREAD

**Issue by xmagor** [jon85p/pyENL#38]
Cuando se usan unidades de temperatura en Celsius, solo la reconoce si se coloca [°C], pero al parecer algo ocurre con la codificación porque cuando se abre el archivo queda [Â°C]

**Comment by jon85p** [comment]
Puede confirmar con este commit en la rama beta1
https://github.com/jon85p/pyENL/commit/a17b58c5111ed1aa817b55e11503f73480402c97
